const products = [
  {
    _id: "1",
    name: "Whiskey Sour",
    image: "/images/products/whiskeysour.webp",
    description: "yayayayayayya",
    brand: "",
    category: "Womenswear",
    price: 9,
    countInStock: 2,
    rating: 4.5,
    numReviews: 5,
  },
  {
    _id: "2",
    name: "Negroni",
    image: "/images/products/negroni.webp",
    description: "yayayayayayya",
    brand: "",
    category: "Menswear",
    price: 12,
    countInStock: 2,
    rating: 2.5,
    numReviews: 5,
  },
  {
    _id: "3",
    name: "Long Island Iced Tea",
    image: "/images/products/longislandicedtea.webp",
    description: "yayayayayayya",
    brand: "",
    category: "Menswear",
    price: 5,
    countInStock: 2,
    rating: 4.5,
    numReviews: 5,
  },
  {
    _id: "4",
    name: "Pina Colada",
    image: "/images/products/pinacolada.webp",
    description: "yayayayayayya",
    brand: "",
    category: "Menswear",
    price: 100,
    countInStock: 2,
    rating: 4.5,
    numReviews: 5,
  },
  {
    _id: "5",
    name: "Pisco Sour",
    image: "/images/products/piscosour.webp",
    description: "yayayayayayya",
    brand: "",
    category: "Menswear",
    price: 100,
    countInStock: 2,
    rating: 4.5,
    numReviews: 5,
  },
  {
    _id: "6",
    name: "Irish Coffee",
    image: "/images/products/irishcoffee.webp",
    description: "yayayayayayya",
    brand: "",
    category: "Menswear",
    price: 100,
    countInStock: 2,
    rating: 4.5,
    numReviews: 5,
  },
];

export default products;
